import os
from github import Github

def get_github():
    return Github(os.getenv("GITHUB_TOKEN"))

def create_branch(repo, branch_name, base="main"):
    base_branch = repo.get_branch(base)
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_branch.commit.sha)

def create_file(repo, path, content, branch):
    repo.create_file(
        path = path,
        message = "AI GEN FIX",
        content = content,
        branch = branch
    )

def create_pr(repo, branch):
    return repo.create_pull(
        title="AI Fix: Bug resolved",
        body="This PR was generated by AI agents.",
        head=branch,
        base="main"
    )

